### ISSUE TITLE
Page is not scrollable after closing modal

### ISSUE THREAD

**Issue by nikolasp** [pleerock/ng2-modal#11]
Body element after closing dialog still has class `modal-open`. Is anyone else experiencing the same problem?

**Comment by nikolasp** [comment]
Hi @pleerock, 

You must change this line https://github.com/pleerock/ng2-modal/blob/master/src/Modal.ts#L128 to something like this

`document.body.className = document.body.className.replace(/modal-open\b/, "");` 

because you are not assigning a new value.

**Comment by pleerock** [comment]
@nikolasp hi, thank you. I released this in 0.0.15
