### ISSUE TITLE
html5 standards should have camel case

### ISSUE THREAD

**Issue by gravity-addiction** [pleerock/ng2-modal#2]
it's brought to my attention that to be html5 compliant, the component needs to have a camelcase.. for instance change Modal to ng2Modal would be correct here.

**Comment by pleerock** [comment]
I was thinking to make it `ng2-modal.ts` instead of `Modal.ts` and it will look like:

import "ng2-modal/ng2-modal";

This is what Im doing in all my other modules. Having ng2-modal/ng2Modal is ugly. Can you provide a link to html5 standards where they say that namespaces must be in camel case?

**Comment by gravity-addiction** [comment]
I believe this is what was being referenced. http://w3c.github.io/webcomponents/spec/custom/#valid-custom-element-name
requiring a dash in your custom element name, is forcing camelcase on us.
```
PotentialCustomElementName ::=
[a-z] (PCENChar)* '-' (PCENChar)*
```

**Comment by gravity-addiction** [comment]
also we are on the same page, ng2-modal as the element ng2-modal/ng2-modal.ts is what i've done as well. which makes the class in the .ts named ng2Modal.

**Comment by pleerock** [comment]
lets left it modal for now.
