### ISSUE TITLE
[Feature Request] ability to hide header/body/footer sections independently

### ISSUE THREAD

**Issue by strictd** [pleerock/ng2-modal#20]
along the lines of adding to Modal.ts with corresponding *ngIf="showHeader" in the template divs

```typescript
    @Input()
    showHeader = true;

    @Input()
    showBody = true;

    @Input()
    showFooter = true;
```

**Comment by pleerock** [comment]
can you simply hide/show <modal-footer> and / or <modal-header> instead?

**Comment by strictd** [comment]
yes, binding to [hidden]="!showHeader" or something similar would work as well.

for single modal window instances I can simply use css on .modal-header .modal-footer { display: none; } however this forces that style for all modals in a given scope.

**Comment by pleerock** [comment]
I don't think this is necessary feature, if someone need it simply should hide/show it?

**Comment by strictd** [comment]
could you provide an example on how you propose to simple hide/show it?

**Comment by strictd** [comment]
unable to use any method to currently hide the header and footer in any manner. If i use the CSS file, then it hides all headers and footers for all modals on the page. Should I put in a bug request for that situation then?
