### ISSUE TITLE
how to open modal popup dynamically

### ISSUE THREAD

**Issue by devendrar** [pleerock/ng2-modal#29]
Hi,

I wanted to open modal popup dynamically using ng2-modal. how to open modal popup dynamically. Please explain it through example.

Thanks.

**Comment by samthomson** [comment]
To access the modal from your js/ts code you should import ViewChild from core and then create a reference/instance to your modal in your code like this:

`@ViewChild('myModal') myModal:any;`

you can then call

`myModal.open();`

**Comment by pleerock** [comment]
I think @samthomson already gave an answer.
