### ISSUE TITLE
HOw to open modal from code

### ISSUE THREAD

**Issue by zivlevy** [pleerock/ng2-modal#31]
Is there a way to open the modal from the component code ?

**Comment by strictd** [comment]
what do you mean exactly? I use the ViewChild decorator to access the modal. like so

component code
```
@ViewChild('MyModal') MyModal;

ngAfterViewInit() {
  this.MyModal.open();
}
```

html code
```
<modal #MyModal>
  <modal-content></modal-content>
</modal>
```

**Comment by zivlevy** [comment]
Thanks, exactly what I needed !

**Comment by pleerock** [comment]
thanks @strictd
