### ISSUE TITLE
Passing Data to a modal

### ISSUE THREAD

**Issue by aryasunny** [pleerock/ng2-modal#4]
Would you have a smaple where you are passing data to a modal.

**Comment by pleerock** [comment]
What do you mean? To show something in the modal you need to use `<modal-content>your content inside modal</modal-content>`

**Comment by pleerock** [comment]
Also you can use providers as described in angular documentation.

**Comment by uzumakinaruto123** [comment]
@pleerock  @aryasunny  The doubt is correct. Its not about showing data in modal content.
Question meant passing some parameters inside modal.

for example , clicking a product from a product list opens a modal. each product having a id. Passing parameter like id while opening will be helpfull to know which product was clicked and information can be loaded dynamically.

Something like this, 

`<button (click)="openModal('hello')">open my modal</button>`

This 'hello' string can be displayed inside modal.

related links :- [SO Iink1](http://stackoverflow.com/questions/24323895/send-parameter-to-bootstrap-modal-window)  and [SO link2](http://stackoverflow.com/questions/10626885/passing-data-to-a-bootstrap-modal)


This can be done , was just wondering if t ng2-modal already supports it.

**Comment by pleerock** [comment]
@uzumakinaruto123 are you talking about data attributes for modal? if yes, then what is the purpose of having them when you don't use jquery?

**Comment by uzumakinaruto123** [comment]
no no ! anyways , can we open modal from component class ?

**Comment by pleerock** [comment]
```html
<div class="row">
    <button (click)="myModal.open()">open my modal</button>
    <modal #myModal>
        <modal-header>
            <h1>Modal header</h1>
        </modal-header>
        <modal-content>
            Hello Modal!
        </modal-content>
        <modal-footer>
            <button class="btn btn-primary" (click)="myModal.close()">close</button>
        </modal-footer>
    </modal>
</div>
```
I still can't get what you are asking. Are you talking about `myModal.open()`? If you are asking how to open modal from typescript code, you can use `@ViewChild("myModal") myModal` and then call `this.myModal.open()`

**Comment by uzumakinaruto123** [comment]
yes fine ! that will help :)  i am talking about passing some variable inside the modal from outside.
I tried explaning above , i will try again . 

I have 5 products with name product1 product2 and so on, clicking on each product opens a modal.
Now as the modal opens , how will i know which product out of the 5 i clicked ? 

And how will i display the name of that product inside modal ?

**Comment by pleerock** [comment]
you can store clicked product in `selectedProduct` variable in your component and simply use bindings and show this variable in the modal

**Comment by uzumakinaruto123** [comment]
ya i figured that. I just thought it already has some ng2 way to do it since its a ng2 wrapper. Thanks for the repo :)

**Comment by pleerock** [comment]
its already ng2 way =) but you can suggest more ng2 way if you know such =)
