### ISSUE TITLE
Can't work on Angular 2.0.0-rc.4

### ISSUE THREAD

**Issue by tuoitrexuquang** [pleerock/ng2-modal#5]
Hi,
I get error message when implement it "No Directive annotation found on Modal", Please help me check
Noted: added directives: [Modal]
Many thanks,

**Comment by pleerock** [comment]
Im using it with Angular 2.0.0-rc.4 and have no problems with it. Make sure your imports is correct and your system.js configuration is correct too

**Comment by tuoitrexuquang** [comment]
Sorry, i still get error message
"Error: Uncaught (in promise): No Directive annotation found on Modal"
"Error: Uncaught (in promise): No Directive annotation found on Modal"

I'm using Angular Webpack
"@angular/common": "^2.0.0-rc.4",
    "@angular/compiler": "^2.0.0-rc.4",
    "@angular/core": "^2.0.0-rc.4",
    "@angular/http": "^2.0.0-rc.4",
    "@angular/platform-browser": "^2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.4",
    "@angular/platform-server": "^2.0.0-rc.4",
    "@angular/router": "^3.0.0-beta.2",
    "@angular/router-deprecated": "^2.0.0-rc.2",
    "angular2-jwt": "^0.1.16",
    "core-js": "^2.2.2",
    "rxjs": "^5.0.0-beta.10",
    "zone.js": "^0.6.12"

Could you pls have a look again?

Thanks

**Comment by pleerock** [comment]
have you ever install any other third party library for angular2? process should be same. Read [installation guide](https://github.com/pleerock/ng2-modal#installation)

**Comment by tuoitrexuquang** [comment]
Yes, i did. and i did follow this guide.  Not work now :(
