### ISSUE TITLE
closeOnEscape does not close

### ISSUE THREAD

**Issue by kennethkoontz** [pleerock/ng2-modal#6]
`[closeOnEscape]="true"` doesn't work.

Here's a [plunkr](http://embed.plnkr.co/O2V3a18MLn2EMicRsHWh/).

**Comment by pleerock** [comment]
fixed in 0.0.7

**Comment by kennethkoontz** [comment]
Sweet thanks!

Ken Koontz

On Thu, Jul 14, 2016 at 7:07 AM Umed Khudoiberdiev

<
mailto:Umed Khudoiberdiev <notifications@github.com>
> wrote:

fixed in 0.0.7

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/pleerock/ng2-modal/issues/6#issuecomment-232675692
, or
https://github.com/notifications/unsubscribe/AAeekCL5Xq1Fx2N8XVD5i0GNGTGQuoWiks5qVkKVgaJpZM4JMF7u
.

https://github.com/pleerock/ng2-modal/issues/6#issuecomment-232675692
